"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Film, Image, Loader2, Mic2, Sparkles, Subtitles, WandSparkles } from "lucide-react";
import { useState } from "react";

type Project = { title:string; duration:number; status:string; hook?:string; script?:string; scenes?:{number:number;title:string;visual:string;duration:number}[]; voice?:{status:string;style:string}; subtitles?:{start:number;end:number;text:string}[]; render?:{status:string;format:string;resolution:string}; seo?:{title:string;description:string;tags:string[]} };

const stages=[['Script AI',WandSparkles],['Voice-over',Mic2],['Visual & Scene',Image],['Subtitle',Subtitles],['Render MP4',Film]] as const;

export default function CreatePage(){
 const [duration,setDuration]=useState(7),[topic,setTopic]=useState(''),[loading,setLoading]=useState(false),[result,setResult]=useState<Project|null>(null),[error,setError]=useState('');
 async function generate(){setLoading(true);setError('');setResult(null);try{const res=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic,duration})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Gagal membuat project.');setResult(data.project)}catch(e){setError(e instanceof Error?e.message:'Terjadi kesalahan.')}finally{setLoading(false)}}
 return <main className="create-shell"><nav className="dash-nav"><Link href="/" className="brand"><span className="brand-mark">S</span><span>SALVIAN <b>AI VIDEO</b></span></Link><div className="user-pill">100 kredit</div></nav><section className="create-main"><Link href="/dashboard" className="back"><ArrowLeft size={16}/> Dashboard</Link><div className="create-title"><div className="eyebrow">CREATE VIDEO</div><h1>Ubah ide menjadi video.</h1><p>Masukkan topik. Mesin produksi akan menyiapkan naskah, scene, voice, subtitle, SEO, hingga antrean MP4.</p></div><div className="stage-strip">{stages.map(([name,Icon],i)=><div className="stage" key={name}><span>{i+1}</span><Icon size={16}/><b>{name}</b></div>)}</div><div className="form-card"><label>TOPIK VIDEO</label><textarea value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Contoh: Rahasia zikir qolbi dalam kajian tasawuf..." disabled={loading}/><label>DURASI VIDEO</label><div className="duration-grid">{[5,6,7,8].map(d=><button type="button" key={d} className={duration===d?'active':''} onClick={()=>setDuration(d)} disabled={loading}><Clock3 size={17}/><strong>{d} menit</strong><span>{d===5?'Ringkas':d===8?'Mendalam':'Standar'}</span></button>)}</div>{error&&<div className="error-box">{error}</div>}{result&&<div className="result-card"><div className="result-head"><div><div className="eyebrow">PROJECT READY</div><h2>{result.title}</h2><p>{result.status} · {result.duration} menit</p></div><CheckCircle2 size={28}/></div><div className="result-grid"><article><span>HOOK</span><p>{result.hook}</p></article><article><span>VOICE</span><p>{result.voice?.style||'Narator Indonesia natural'}</p></article><article><span>RENDER</span><p>{result.render?.format||'MP4'} · {result.render?.resolution||'1080p'} · {result.render?.status||'queued'}</p></article></div><article className="script-preview"><span>NASKAH</span><p>{result.script}</p></article>{result.scenes&&<div className="scene-list">{result.scenes.slice(0,8).map(s=><div className="scene-item" key={s.number}><b>{s.number}</b><div><strong>{s.title}</strong><p>{s.visual}</p></div><small>{s.duration}s</small></div>)}</div>}<div className="seo-box"><span>YOUTUBE SEO</span><strong>{result.seo?.title||result.title}</strong><p>{result.seo?.description}</p><small>{result.seo?.tags?.join(' · ')}</small></div></div>}{<div className="form-footer"><span><Sparkles size={16}/> Perkiraan: 25 kredit</span><button className="primary" disabled={!topic.trim()||loading} onClick={generate}>{loading?<><Loader2 size={17} className="spin"/> Memproduksi...</>:<>Buat Project <ArrowRight size={17}/></>}</button></div>}</div></section></main>;
}
