"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Copy, Film, Image as ImageIcon, Layers3, Loader2, Mic2, Music2, Play, Plus, Save, Scissors, Sparkles, Subtitles, Trash2, WandSparkles, Upload, Volume2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";

type Scene={number:number;title:string;visual:string;duration:number;voice:string};
type Project={title:string;duration:number;status:string;hook?:string;script?:string;scenes?:Scene[];voice?:{status:string;style:string};render?:{status:string;format:string;resolution:string};seo?:{title:string;description:string;tags:string[]}};

const stages=[['Script AI',WandSparkles,'Script'],['Storyboard',Layers3,'Storyboard'],['Voice-over',Mic2,'Audio'],['Visual',ImageIcon,'Visual'],['Music',Music2,'Audio'],['Subtitle',Subtitles,'Subtitle'],['Render',Film,'Timeline']] as const;
const tabs=['Konsep','Script','Storyboard','Audio','Visual','Subtitle','Timeline'];
const durations=[5,6,7,8];
const defaultScenes:Scene[]=[
 {number:1,title:'Opening / Hook',visual:'Cinematic establishing shot, subject utama, title overlay.',duration:35,voice:'Pembuka kuat dan menarik perhatian penonton.'},
 {number:2,title:'Konteks Masalah',visual:'B-roll relevan dengan topik, medium shots dan detail.',duration:55,voice:'Jelaskan konteks dan masalah dengan bahasa sederhana.'},
 {number:3,title:'Pembahasan Utama',visual:'Sequence visual utama dengan variasi angle dan pacing.',duration:75,voice:'Masuk ke inti pembahasan dan berikan contoh.'},
 {number:4,title:'Insight / Turning Point',visual:'Visual emosional, close-up, cinematic transition.',duration:60,voice:'Sampaikan insight penting yang menjadi titik balik.'},
 {number:5,title:'Kesimpulan',visual:'Montage penutup, visual yang tenang dan memorable.',duration:45,voice:'Rangkum pesan utama dan ajak penonton bertindak.'},
];

export default function CreatePage(){
 const [duration,setDuration]=useState(7),[topic,setTopic]=useState(''),[style,setStyle]=useState('Cinematic'),[ratio,setRatio]=useState('16:9'),[language,setLanguage]=useState('Indonesia'),[voice,setVoice]=useState('Narator Natural'),[music,setMusic]=useState('Ambient Cinematic');
 const [loading,setLoading]=useState(false),[result,setResult]=useState<Project|null>(null),[error,setError]=useState(''),[activeTab,setActiveTab]=useState('Konsep'),[previewing,setPreviewing]=useState(false),[projectTitle,setProjectTitle]=useState(''),[projectStatus,setProjectStatus]=useState('Draft');
 const [autoStoryboard,setAutoStoryboard]=useState(true),[autoSubtitle,setAutoSubtitle]=useState(true),[smartPacing,setSmartPacing]=useState(true);
 const [scenes,setScenes]=useState<Scene[]>(defaultScenes),[selectedScene,setSelectedScene]=useState(1);
 const totalSceneTime=useMemo(()=>scenes.reduce((sum,s)=>sum+s.duration,0),[scenes]);
 useEffect(()=>{
  const params=new URLSearchParams(window.location.search);
  const requestedTitle=params.get('project'); const requestedTab=params.get('tab');
  const rawActive=localStorage.getItem('salvian-video-active-project'); const rawWorkspace=localStorage.getItem('salvian-video-workspace');
  let active:{title?:string;status?:string;duration?:string}|null=null; let workspace:{title?:string;status?:string;duration?:string}|null=null;
  try{if(rawActive)active=JSON.parse(rawActive);}catch{} try{if(rawWorkspace)workspace=JSON.parse(rawWorkspace);}catch{}
  const title=requestedTitle||active?.title||workspace?.title; if(title)setProjectTitle(title);
  if(active?.status)setProjectStatus(active.status); else if(workspace?.status)setProjectStatus(workspace.status);
  if(workspace?.duration){const match=workspace.duration.match(/\d+/);if(match)setDuration(Number(match[0]));}
  if(requestedTab&&tabs.includes(requestedTab))setActiveTab(requestedTab);
  const rawDraft=localStorage.getItem('salvian-video-draft');
  try{if(rawDraft){const draft=JSON.parse(rawDraft);if(!title||draft.projectTitle===title){if(draft.topic)setTopic(draft.topic);if(draft.duration)setDuration(draft.duration);if(draft.style)setStyle(draft.style);if(draft.ratio)setRatio(draft.ratio);if(draft.language)setLanguage(draft.language);if(draft.voice)setVoice(draft.voice);if(draft.music)setMusic(draft.music);if(Array.isArray(draft.scenes))setScenes(draft.scenes);}}}catch{}
 },[]);
 async function generate(){setLoading(true);setError('');setResult(null);try{const res=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic,duration,style,ratio,language,voice,music,autoStoryboard,autoSubtitle,smartPacing})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Gagal membuat project.');setResult(data.project);if(data.project?.scenes?.length)setScenes(data.project.scenes);}catch(e){setError(e instanceof Error?e.message:'Terjadi kesalahan.')}finally{setLoading(false)}}
 function saveDraft(){const savedProject={title:projectTitle||topic||'Project Video Baru',status:projectStatus||'Draft',duration:`${duration} menit`};localStorage.setItem('salvian-video-draft',JSON.stringify({projectTitle:savedProject.title,topic,duration,style,ratio,language,voice,music,autoStoryboard,autoSubtitle,smartPacing,scenes}));localStorage.setItem('salvian-video-workspace',JSON.stringify({...savedProject,updatedAt:new Date().toISOString()}));localStorage.setItem('salvian-video-active-project',JSON.stringify(savedProject));setProjectTitle(savedProject.title);setError('Draft tersimpan dan project aktif diperbarui.');setTimeout(()=>setError(''),2500)}
 function addScene(){setScenes(prev=>[...prev,{number:prev.length+1,title:`Scene ${prev.length+1}`,visual:'Tambahkan arahan visual scene...',duration:45,voice:'Tambahkan narasi scene...'}])}
 function removeScene(n:number){setScenes(prev=>prev.filter(s=>s.number!==n).map((s,i)=>({...s,number:i+1})))}
 function duplicateScene(n:number){const source=scenes.find(s=>s.number===n);if(!source)return;setScenes(prev=>[...prev,{...source,number:prev.length+1,title:`${source.title} Copy`}])}
 function updateScene(n:number,key:keyof Scene,value:string|number){setScenes(prev=>prev.map(s=>s.number===n?{...s,[key]:value}:s))}
 function preview(){setPreviewing(true);setTimeout(()=>setPreviewing(false),1800)}
 const workspaceHref=projectTitle?`/workspace?project=${encodeURIComponent(projectTitle)}`:'/workspace';
 return <main className="create-shell">
  <nav className="dash-nav"><Link href="/" className="brand"><span className="brand-mark">S</span><span>SALVIAN <b>AI VIDEO</b></span></Link><div className="studio-nav-actions"><span className="user-pill">2.500 kredit</span><Link href={workspaceHref} className="secondary-btn">Workspace</Link></div></nav>
  <section className="create-main">
   <Link href={workspaceHref} className="back"><ArrowLeft size={16}/> {projectTitle?'Kembali ke Workspace':'Dashboard'}</Link>
   <div className="studio-title"><div><div className="eyebrow">VIDEO STUDIO · LONG FORM</div><h1>Produksi video 5–8 menit.</h1><p>{projectTitle?<>Project aktif: <strong>{projectTitle}</strong> · {projectStatus}</>:<>Workspace profesional untuk membangun script, storyboard, audio, visual, subtitle, timeline, sampai render akhir.</>}</p></div><button className="secondary-btn" type="button" onClick={saveDraft}><Save size={16}/> Simpan Draft</button></div>
   <div className="stage-strip studio-stages">{stages.map(([name,Icon,target],i)=><button type="button" className={`stage stage-button ${activeTab===target?'stage-active':''}`} key={name} onClick={()=>setActiveTab(target)}><span>{i+1}</span><Icon size={15}/><b>{name}</b></button>)}</div>
   <div className="studio-layout"><div className="studio-editor">
    <div className="tab-bar">{tabs.map(t=><button type="button" key={t} className={activeTab===t?'tab-active':''} onClick={()=>setActiveTab(t)}>{t}</button>)}</div>
    {activeTab==='Konsep'&&<div className="form-card studio-card"><SectionHead eyebrow="01 · CONCEPT" title="Konsep Produksi" right={<span className="ready-pill"><CheckCircle2 size={14}/> UI siap</span>}/><label>IDE / TOPIK VIDEO</label><textarea value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Contoh: Rahasia zikir qolbi dan perjalanan batin seorang pencari makrifat..." disabled={loading}/><div className="control-grid"><Control label="DURASI"><div className="choice-row">{durations.map(d=><button type="button" key={d} className={duration===d?'choice-active':''} onClick={()=>setDuration(d)} disabled={loading}><Clock3 size={14}/>{d} mnt</button>)}</div></Control><Control label="RASIO"><div className="choice-row">{['16:9','9:16','1:1'].map(x=><button type="button" key={x} className={ratio===x?'choice-active':''} onClick={()=>setRatio(x)}>{x}</button>)}</div></Control><Control label="GAYA VISUAL"><select value={style} onChange={e=>setStyle(e.target.value)}><option>Cinematic</option><option>Documentary</option><option>Realistic</option><option>Anime</option><option>Islamic Elegant</option></select></Control><Control label="BAHASA"><select value={language} onChange={e=>setLanguage(e.target.value)}><option>Indonesia</option><option>English</option><option>Malay</option></select></Control><Control label="VOICE-OVER"><select value={voice} onChange={e=>setVoice(e.target.value)}><option>Narator Natural</option><option>Narator Deep</option><option>Narator Warm</option><option>Storytelling</option></select></Control><Control label="MUSIK LATAR"><select value={music} onChange={e=>setMusic(e.target.value)}><option>Ambient Cinematic</option><option>Emotional Piano</option><option>Documentary</option><option>Minimal</option><option>Tanpa Musik</option></select></Control></div><div className="feature-switches"><Toggle title="Auto Storyboard" text="Pecah naskah menjadi scene otomatis" value={autoStoryboard} onChange={setAutoStoryboard}/><Toggle title="Auto Subtitle" text="Sinkronkan subtitle dengan voice-over" value={autoSubtitle} onChange={setAutoSubtitle}/><Toggle title="Smart Pacing" text="Sesuaikan tempo antar scene" value={smartPacing} onChange={setSmartPacing}/></div>{error&&<div className="error-box">{error}</div>}<div className="form-footer studio-footer"><span><Sparkles size={16}/> Estimasi awal: 25 kredit · {duration} menit · {ratio}</span><button className="primary" disabled={!topic.trim()||loading} onClick={generate}>{loading?<><Loader2 size={17} className="spin"/> Menyiapkan project...</>:<>Buat Project <ArrowRight size={17}/></>}</button></div></div>}
    {activeTab==='Storyboard'&&<Storyboard scenes={scenes} selected={selectedScene} onSelect={setSelectedScene} onAdd={addScene} onRemove={removeScene} onDuplicate={duplicateScene} onUpdate={updateScene}/>} 
    {activeTab==='Script'&&<ScriptPanel topic={topic} duration={duration} scenes={scenes}/>} 
    {activeTab==='Audio'&&<AudioPanel voice={voice} music={music} language={language}/>} 
    {activeTab==='Visual'&&<VisualPanel style={style}/>} 
    {activeTab==='Subtitle'&&<SubtitlePanel language={language} auto={autoSubtitle}/>} 
    {activeTab==='Timeline'&&<Timeline scenes={scenes} total={totalSceneTime} projectTitle={projectTitle||topic||'Project Video Baru'}/>} 
    {result&&<Result project={result}/>} 
   </div>
   <aside className="preview-panel"><div className="preview-head"><div><div className="eyebrow">LIVE PREVIEW</div><strong>Canvas {ratio}</strong></div><span className="preview-dot">{previewing?'PLAYING':'READY'}</span></div><div className="video-preview" style={{aspectRatio:ratio.replace(':','/')}}><div className="preview-grid"></div><button type="button" className="preview-center" onClick={preview} aria-label="Preview video"><Play size={22}/></button><span>{previewing?'Memutar preview...':'Preview video akan muncul di sini'}</span></div><div className="preview-meta"><div><span>SCENE</span><strong>{scenes.length}</strong></div><div><span>DURASI</span><strong>{Math.floor(totalSceneTime/60)}:{String(totalSceneTime%60).padStart(2,'0')}</strong></div><div><span>OUTPUT</span><strong>MP4</strong></div></div><button className="secondary-btn full" type="button" onClick={preview}><Play size={15}/> Preview Timeline</button><div className="preview-actions"><button type="button" onClick={()=>setActiveTab('Visual')}><Upload size={14}/> Asset</button><button type="button" onClick={()=>setActiveTab('Audio')}><Volume2 size={14}/> Audio</button><button type="button" onClick={()=>setActiveTab('Timeline')}><Scissors size={14}/> Cut</button></div></aside>
   </div>
  </section>
 </main>;
}

function SectionHead({eyebrow,title,right}:{eyebrow:string;title:string;right?:ReactNode}){return <div className="section-heading"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div>{right}</div>}
function Control({label,children}:{label:string;children:ReactNode}){return <div className="control"><label>{label}</label>{children}</div>}
function Toggle({title,text,value,onChange}:{title:string;text:string;value:boolean;onChange:(v:boolean)=>void}){return <button className="toggle" type="button" onClick={()=>onChange(!value)}><div><strong>{title}</strong><span>{text}</span></div><div className={`toggle-ui ${value?'is-on':''}`}></div></button>}

function Storyboard({scenes,selected,onSelect,onAdd,onRemove,onDuplicate,onUpdate}:{scenes:Scene[];selected:number;onSelect:(n:number)=>void;onAdd:()=>void;onRemove:(n:number)=>void;onDuplicate:(n:number)=>void;onUpdate:(n:number,key:keyof Scene,value:string|number)=>void}){const current=scenes.find(s=>s.number===selected);return <div className="form-card studio-card"><SectionHead eyebrow="02 · STORYBOARD" title="Scene Builder" right={<button className="secondary-btn" type="button" onClick={onAdd}><Plus size={15}/> Tambah Scene</button>}/><div className="storyboard-layout"><div className="scene-list studio-scenes">{scenes.map(s=><button type="button" key={s.number} className={`scene-item ${selected===s.number?'scene-selected':''}`} onClick={()=>onSelect(s.number)}><b>{String(s.number).padStart(2,'0')}</b><div><strong>{s.title}</strong><p>{s.visual}</p></div><small>{s.duration}s</small></button>)}</div><div className="scene-editor">{current?<><div className="editor-toolbar"><span>SCENE {String(selected).padStart(2,'0')}</span><div><button type="button" onClick={()=>onDuplicate(selected)}><Copy size={14}/></button><button type="button" onClick={()=>onRemove(selected)} disabled={scenes.length<=1}><Trash2 size={14}/></button></div></div><label>JUDUL SCENE</label><input value={current.title} onChange={e=>onUpdate(selected,'title',e.target.value)}/><label>ARAHAN VISUAL</label><textarea value={current.visual} onChange={e=>onUpdate(selected,'visual',e.target.value)}/><label>NARASI / VOICE-OVER</label><textarea value={current.voice} onChange={e=>onUpdate(selected,'voice',e.target.value)}/><label>DURASI SCENE · DETIK</label><input type="number" min={3} value={current.duration} onChange={e=>onUpdate(selected,'duration',Number(e.target.value)||3)}/></>:<div className="empty-state">Belum ada scene.</div>}</div></div></div>}

function ScriptPanel({topic,duration,scenes}:{topic:string;duration:number;scenes:Scene[]}){const [script,setScript]=useState(scenes.map(s=>`${s.title}\n${s.voice}\n`).join('\n'));const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');async function regenerate(){if(!topic.trim()){setMessage('Isi topik terlebih dahulu di tab Konsep.');return}setBusy(true);setMessage('');try{const res=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic,duration,style:'Cinematic',ratio:'16:9',language:'Indonesia',voice:'Narator Natural',music:'Ambient Cinematic',autoStoryboard:true,autoSubtitle:true,smartPacing:true})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Gagal membuat script.');const p=data.project as Project;setScript(p.script||p.scenes?.map(s=>`${s.title}\n${s.voice}\n`).join('\n')||'');setMessage('Script berhasil diperbarui dari generator.')}catch(e){setMessage(e instanceof Error?e.message:'Gagal membuat script.')}finally{setBusy(false)}}return <div className="form-card studio-card"><SectionHead eyebrow="03 · SCRIPT AI" title="Naskah Panjang" right={<span className="ready-pill"><WandSparkles size={14}/> Generator aktif</span>}/><div className="script-workspace"><div className="script-note"><Sparkles size={17}/><div><strong>Target naskah {duration} menit</strong><span>Topik: {topic||'Belum ada topik. Kembali ke Konsep untuk mengisi ide.'}</span></div></div><textarea className="large-editor" value={script} onChange={e=>setScript(e.target.value)} placeholder="Naskah hasil AI akan tampil di sini..."/><div className="editor-stats"><span>{Math.max(0,Math.round(duration*1300/10)*10)}–{duration*1500} karakter target</span><span>Scene {scenes.length}</span><button type="button" className="secondary-btn" onClick={regenerate} disabled={busy}>{busy?<><Loader2 size={14} className="spin"/> Membuat...</>:<><WandSparkles size={14}/> Regenerate Script</>}</button></div>{message&&<div className="error-box">{message}</div>}</div></div>}
function AudioPanel({voice,music,language}:{voice:string;music:string;language:string}){return <div className="form-card studio-card"><SectionHead eyebrow="04 · AUDIO" title="Voice & Music"/><div className="audio-cards"><AudioCard icon={<Mic2/>} title="Voice-over" value={voice} status="Konfigurasi dari Konsep"/><AudioCard icon={<Music2/>} title="Background Music" value={music} status="Konfigurasi dari Konsep"/><AudioCard icon={<Volume2/>} title="Language Mix" value={language} status="Target bahasa"/></div><div className="waveform"><div className="wave-bars">{Array.from({length:70},(_,i)=><i key={i} style={{height:`${18+((i*37)%65)}%`}}/> )}</div><span>Audio timeline · engine akan dihubungkan setelah integrasi provider</span></div></div>}
function AudioCard({icon,title,value,status}:{icon:ReactNode;title:string;value:string;status:string}){return <div className="audio-card"><div className="audio-icon">{icon}</div><div><span>{title}</span><strong>{value}</strong><small>{status}</small></div><button type="button" aria-label={`Buka ${title}`}><ArrowRight size={15}/></button></div>}
function VisualPanel({style}:{style:string}){const [assets,setAssets]=useState<string[]>([]);return <div className="form-card studio-card"><SectionHead eyebrow="05 · VISUAL" title="Visual & Assets" right={<label className="secondary-btn upload-label"><Upload size={15}/> Upload Asset<input type="file" accept="image/*,video/*" hidden onChange={e=>{const f=e.target.files?.[0];if(f)setAssets(a=>[...a,f.name])}}/></label>}/><div className="asset-grid">{['Scene Preview','Character Reference','B-roll Library','Background / Overlay','Thumbnail Frame','Logo / Brand'].map((x,i)=><div className="asset-card" key={x}><div className="asset-placeholder"><ImageIcon size={22}/><span>{i<2?'GENERATE':'DROP ASSET'}</span></div><strong>{x}</strong><small>{style} · 16:9</small></div>)}</div>{assets.length>0&&<div className="script-note"><Upload size={16}/><div><strong>Asset terunggah</strong><span>{assets.join(' · ')}</span></div></div>}</div>}
function SubtitlePanel({language,auto}:{language:string;auto:boolean}){return <div className="form-card studio-card"><SectionHead eyebrow="06 · SUBTITLE" title="Subtitle Studio" right={<span className="ready-pill"><Subtitles size={14}/> {auto?'AUTO ON':'MANUAL'}</span>}/><div className="subtitle-preview"><div className="subtitle-video"><span>PREVIEW VIDEO</span><strong>Subtitle akan tersinkron dengan voice-over</strong></div><div className="subtitle-controls"><label>Bahasa <select defaultValue={language}><option>Indonesia</option><option>English</option><option>Malay</option></select></label><label>Style <select><option>Clean White</option><option>Bold Creator</option><option>Minimal</option></select></label><label>Position <select><option>Bottom</option><option>Center</option><option>Top</option></select></label></div></div></div>}
function Timeline({scenes,total,projectTitle}:{scenes:Scene[];total:number;projectTitle:string}){let cursor=0;return <div className="form-card studio-card"><SectionHead eyebrow="07 · TIMELINE" title="Video Timeline" right={<span className="ready-pill"><CheckCircle2 size={14}/> {scenes.length} scenes</span>}/><div className="timeline-ruler">{Array.from({length:9},(_,i)=><span key={i}>{i}m</span>)}</div><div className="timeline-track">{scenes.map(s=>{const left=cursor;cursor+=s.duration;return <button type="button" key={s.number} className="timeline-clip" style={{width:`${Math.max(9,s.duration/Math.max(total,1)*100)}%`}}><b>{s.number}</b><span>{s.title}</span><small>{s.duration}s</small><i style={{left:`${left/Math.max(total,1)*100}%`}}/></button>})}</div><div className="timeline-lanes"><div><span>VIDEO</span><div className="lane-fill">Scene clips</div></div><div><span>VOICE</span><div className="lane-audio">Voice-over</div></div><div><span>MUSIC</span><div className="lane-audio">Background music</div></div><div><span>SUBTITLE</span><div className="lane-fill">Auto subtitle</div></div></div><div className="render-panel"><div><strong>Render Final Video</strong><span>MP4 · 1080p · {total} detik timeline</span></div><Link className="primary" href={`/render?project=${encodeURIComponent(projectTitle)}`}><Film size={16}/> Buka Render Center <ArrowRight size={16}/></Link></div></div>}

function Result({project}:{project:Project}){return <div className="result-card"><div className="result-head"><div><div className="eyebrow">PROJECT READY</div><h2>{project.title}</h2><p>{project.status} · {project.duration} menit</p></div><CheckCircle2 size={28}/></div><div className="result-grid"><article><span>HOOK</span><p>{project.hook}</p></article><article><span>VOICE</span><p>{project.voice?.style||'Narator Indonesia natural'}</p></article><article><span>RENDER</span><p>{project.render?.format||'MP4'} · {project.render?.resolution||'1080p'} · {project.render?.status||'queued'}</p></article></div>{project.script&&<article className="script-preview"><span>NASKAH</span><p>{project.script}</p></article>}{project.scenes&&<div className="scene-list">{project.scenes.slice(0,8).map(s=><div className="scene-item" key={s.number}><b>{s.number}</b><div><strong>{s.title}</strong><p>{s.visual}</p></div><small>{s.duration}s</small></div>)}</div>}<div className="seo-box"><span>YOUTUBE SEO</span><strong>{project.seo?.title||project.title}</strong><p>{project.seo?.description}</p><small>{project.seo?.tags?.join(' · ')}</small></div></div>}
